# Generated by Django 4.0.4 on 2022-04-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_offersmicroservicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='external_ms_id',
            field=models.IntegerField(null=True),
        ),
    ]
