# Generated by Django 4.0.4 on 2022-05-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_offer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='external_ms_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=511),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
